<a href="https://colab.research.google.com/github/murali-marimekala/pg-genai-ml/blob/main/Wk3_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# File handling

- Handling external data


In [3]:
# Connect to the tex file. We can create an object using open
f = open("/content/sample_data/README.md")
print(type(f))
f.read()

<class '_io.TextIOWrapper'>


"This directory includes a few sample datasets to get you started.\n\n*   `california_housing_data*.csv` is California housing data from the 1990 US\n    Census; more information is available at:\n    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub\n\n*   `mnist_*.csv` is a small sample of the\n    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is\n    described at: http://yann.lecun.com/exdb/mnist/\n\n*   `anscombe.json` contains a copy of\n    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it\n    was originally described in\n\n    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American\n    Statistician. 27 (1): 17-21. JSTOR 2682899.\n\n    and our copy was prepared by the\n    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).\n"

In [9]:
# Providing mode to open

# open the file in reading mode
f = open("/content/sample_data/README.md", "r")
f.read()

# In write mode
f = open("/content/sample_data/README.md", "w")
f.write("Name is Maratha \n")
f.write("Age is : 36\n")
f.close()

# Append to the end
f = open("/content/sample_data/README.md", "a")
f.write("This will add this line")
f.close()

In [10]:
f = open("/content/sample_data/README.md", "r")
print(f.read())


Name is Maratha 
Age is : 36
This will add this line


# Context Manager

- Context manager is used to manage resources automatically
- It ensures the resource is properly opened and closed properly

In [11]:
# Exampel without context manager
f = open("/content/sample_data/README.md", "r")
data = f.read()
print(data)
f.close()


Name is Maratha 
Age is : 36
This will add this line


In [12]:
# Example with Context manager
with open("/content/sample_data/README.md", "r") as f:
  data = f.read()
  print(data)

Name is Maratha 
Age is : 36
This will add this line


# Numpy

- Python library used for working with numbers and arrays
- Think of NumPy as fast math with arrays
- NumPy is very fast with array calculations
- Numpy Array (NdArray) - Collection of homogeneous items (of same datatype)

## Where numpy is used
- Extensively used in Data analysis, Data science, Machine learning and Artificial intelligence

In [15]:
!pip install numpy

In [16]:
import numpy as np
np.__version__

'2.0.2'

In [24]:
# Creating numpy one dimentional array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr)) # Type of the array
print(arr.ndim) # Dimension of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [21]:
# 2D arry
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [45]:
# 2D Float aray
print("\n2D Float array \n")
arr = np.array([[1.1,2.2,3.3], ['4',5.5,6]], dtype='float32')
print(arr)

# 2D Integer array
print("\n2D Integer array \n")
arr = np.array([[1.1,2.2,3.3], ['4',5.5,6]], dtype='int32')
print(arr)



2D Float array 

[[1.1 2.2 3.3]
 [4.  5.5 6. ]]

2D Integer array 

[[1 2 3]
 [4 5 6]]


In [41]:
arr = np.array([['a','b',3],[1,2,3]])
print(arr)
print(f"Array is of {arr.ndim} Dimensions")

[['a' 'b' '3']
 ['1' '2' '3']]
Array is of 2 Dimensions


In [49]:
# Attributes of numpy array
b = np.array([[1,2,3],[4,5,6]])
print("Dimension : ndim",b.ndim)
print("Shape of the array: shape",b.shape)
print("Overall elements in data : size",b.size)
print("Type of the data: dtype",b.dtype)

Dimension : ndim 2
Shape of the array: shape (2, 3)
Overall elements in data : size 6
Type of the data: dtype int64


In [58]:
# Save the marks of 3 students in 3 subjects
student_marks = np.array ([
    [23,33,33],
    [33,4,5],
    [1,43,5]
])
print(student_marks)
print(student_marks.ndim)
print(student_marks.shape)
print(student_marks.size)
print(student_marks.dtype)

[[23 33 33]
 [33  4  5]
 [ 1 43  5]]
2
(3, 3)
9
int64


In [60]:
# 3 dimensions - > 3 students
# 4 subjects
# 3 exams
marks_3d = np.array([
    [
        [34,24,23],
        [34,2,45],
        [24,23,4],
        [34,2,3]
    ],
    [
        [34,24,23],
        [34,2,45],
        [24,23,23],
        [23,4,2]
    ],
    [
        [34,24,23],
        [34,2,45],
        [24,23,32],
        [3,3,4]
    ]
])
print(marks_3d)
print(marks_3d.ndim)
print(marks_3d.shape)
print(marks_3d.size)
print(marks_3d.dtype)

[[[34 24 23]
  [34  2 45]
  [24 23  4]
  [34  2  3]]

 [[34 24 23]
  [34  2 45]
  [24 23 23]
  [23  4  2]]

 [[34 24 23]
  [34  2 45]
  [24 23 32]
  [ 3  3  4]]]
3
(3, 4, 3)
36
int64


In [69]:
# Indexing and Slicing
arr = np.array([1,2,3,4,5,6])
arr[:2]

array([1, 2])

In [70]:
arr[2:]

array([3, 4, 5, 6])

In [74]:
# 2D array indexing and slicing
# Marks of 3 students in 3 subjects
mat = np.array([
    [1,2,3],
    [3,4,5],
    [6,7,8]
])

#print(mat)
print(mat[0:2])
print(mat.ndim)

[[1 2 3]
 [3 4 5]]
2


In [75]:
mat[1,2]

np.int64(5)

In [79]:
mat[1][2]

np.int64(5)

In [78]:
mat[0:2,1:3]

array([[2, 3],
       [4, 5]])

# Vectorized Operations
- Performing operations on arrays without using loops

In [81]:
# List
nums = [1,2,3,5,6]

nums = [ x * x for x in nums  ]

print(nums)

[1, 4, 9, 25, 36]


In [82]:
a = np.array([1,2,3,4,5])
print(a*a) # Vectorized operation

[ 1  4  9 16 25]


# Aggregation Functions

In [87]:
data = np.array([
    [1,2,3],
     [4,5,6]
    ])
data.sum()


np.int64(21)

In [93]:
data.sum(axis=0)# Sum of first dimension 1+4, 2+5, 3+6

array([5, 7, 9])

In [92]:
data.sum(axis=1) # Dimensions of second dimension.  (1+2+3, 4+5+6)

array([ 6, 15])

In [94]:
data.mean()

np.float64(3.5)

# Performance between numpy and lists

In [96]:
import time

lst = list(range(1000000))
start = time.time()
[x*x for x in lst]
end = time.time()
print("Time taken by list: ", (end-start))

arr = np.array(lst)
start = time.time()
arr = arr*arr
end = time.time()
print("Time taken by array: ", (end-start))

Time taken by list:  0.10845160484313965
Time taken by array:  0.0067522525787353516


# Pandas

- Pandas is a python library used to
  - Work with data in table format
  - Clean and analyze data

In [97]:
import pandas as pd

# Pandas Series

- One dimensional data structure. Like one column in excel

In [100]:
s = pd.Series([10,20,30,40,50])
print(s)
print(type(s))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [110]:
# Series with Custom index
s = pd.Series([10,20,30,40,50], index=['a','b','c','e','f'])
print(s.loc['a']) # Access by label -> use iloc
print(s.iloc[1]) # Access by position -> use iloc

10
20


# Series attributes
- s.values
- s.indedx
- s.dtype

In [113]:
# Series attributes
print(s.values) # Values in the format of array
print(s.index) # Prints indexes
print(s.dtype)


[10 20 30 40 50]
Index(['a', 'b', 'c', 'e', 'f'], dtype='object')
int64


In [114]:
# Arthemetic operation on series
s = pd.Series([10,20,30])
s + 5


0    15
1    25
2    35
dtype: int64

In [115]:
# Filtering Series

s = pd.Series([10,20,30,40,50])
s[s>30]

3    40
4    50
dtype: int64

In [116]:
# Apply funciton
s = pd.Series([10,20,30,40,50])
s.apply(lambda x: x*x)

0     100
1     400
2     900
3    1600
4    2500
dtype: int64

In [117]:
# Missing values in series
s = pd.Series([10,20,30,40,50, None])
s.isna()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [118]:
s = pd.Series([10,20,30,40,50, None])
s.fillna(0)

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5     0.0
dtype: float64

In [119]:
# Droppint the values
s = pd.Series([10,20,30,40,50, None])
s.dropna()

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64

In [122]:
# Fill with a average value
s = pd.Series([10,20,30,40,50, None]) # Fill the None with mean
print(s)
s.fillna(s.mean())

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5     NaN
dtype: float64


0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5    30.0
dtype: float64

In [135]:
print(dir(pd.BooleanDtype.__class__.__base__.__format__.__get__)) ## We get can help using this method or use help

['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__name__', '__ne__', '__new__', '__objclass__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__text_signature__']


# Pandas DataFrame

- A data frame is a table with rows and columns. Note series is one dimensional

In [138]:
data = {
    'Name' : ['Alice','Bob','Charlie'],
    'Age' : [25,30,35],
    'City' : ['New York','San Francisco','Los Angeles']
}

df = pd.DataFrame(data)
df

Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [146]:
# Give names to indexes

df = pd.DataFrame(data, index=["emp1","emp2","emp3"])
df

Name  Age           City
emp1    Alice   25       New York
emp2      Bob   30  San Francisco
emp3  Charlie   35    Los Angeles

In [152]:
# List of dictionaries
data = [
    { 'Name' : 'Alice', 'Age' : 25, 'City' : 'New York'},
    { 'Name' : 'Bob', 'Age' : 30, 'City' : 'San Francisco'},
    { 'Name' : 'Charlie', 'Age' : 35, 'City' : 'Los Angeles'}
]
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles


In [151]:
# From a dictionariy of series
data = {
    'Name' : pd.Series(['Alice','Bob','Charlie']),
    'Age' : pd.Series([25,30,35]),
    'City' : pd.Series(['New York','San Francisco','Los Angeles'])
}

df = pd.DataFrame(data)
df

Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles